---
# Configuration for your virtual machine
vm-config:
    - memory: "2048"
      cpus: "1"

# SSH stuff
authorize: /Users/me/.ssh/id_rsa.pub

keys:
    - /Users/me/.ssh/id_rsa

# Specify the path for each folder you'd like to share with the virtual machine
folders:
    - map: /Users/me/path/to/code
      to: /home/vagrant/path/to/code
    - map: /Users/me/more/code
      to: /home/vagrant/more/code